version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build # 인스턴스에서 파일이 저장될 위치

# ec2-user로 설정해야함
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user

    - location: healthCheck.sh
      timeout: 60
      runas: ec2-user