name: Code Analyze Pull Request

on:
  pull_request:
    branches:
      - develop  # PR이 develop 브랜치로 올 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    # WRITE 권한 부여
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75
          title: "⭐️Code Coverage"
          update-comment: true

      # jacoco
      - name: Upload Jacoco Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report # 결과물의 이름
          path: ${{ github.workspace }}/build/reports/jacoco/test/html/* # upload하고자 하는 파일 또는 디렉토리 경로
